-- create table std(ROLLNO VARCHAR(2),NAME CHAR(10),AGE NUMBER(2));

-- drop table std;

CREATE TABLE AIRLINES(AIRLINE_CODE VARCHAR(20) PRIMARY KEY,
HEAD_ADDRESS VARCHAR(100) NOT NULL,AIRLINE_NAME VARCHAR(30) NOT NULL);

CREATE TABLE AIRPORT(AIRPORT_CODE VARCHAR(15) PRIMARY KEY,AIRPORT_NAME VARCHAR(50) NOT NULL,
CITY VARCHAR(30) NOT NULL,STATE VARCHAR(30) NOT NULL);

desc AIRPORT;

CREATE TABLE PRICEDETAILS(AIRLINE_CODE VARCHAR(15) NOT NULL);
desc AIRLINES;

CREATE TABLE FLIGHT_DESTINATION_AIRPORT(FLIGHT_NUMBER NUMBER,AIRPORT_CODE VARCHAR(15),
FOREIGN KEY(AIRPORT_CODE) REFERENCES)

CREATE TABLE PASSENGER(PASSENGER_ID NUMBER PRIMARY KEY,FIRSTNAME VARCHAR(32) NOT NULL,
MIDDLENAME VARCHAR(32),LASTNAME VARCHAR(32) NOT NULL,DOB DATE NOT NULL,
AGE NUMBER CHECK(LEN(AGE)>0),GENDER CHAR(1),PASSENGER_TYPE VARCHAR(32));
