-- create table std(ROLLNO VARCHAR(2),NAME CHAR(10),AGE NUMBER(2));

-- drop table std;

CREATE TABLE AIRLINES(AIRLINE_CODE VARCHAR(20) PRIMARY KEY,
HEAD_ADDRESS VARCHAR(100) NOT NULL,AIRLINE_NAME VARCHAR(30) NOT NULL);

CREATE TABLE AIRPORT(AIRPORT_CODE VARCHAR(15) PRIMARY KEY,AIRPORT_NAME VARCHAR(50) NOT NULL,
CITY VARCHAR(30) NOT NULL,STATE VARCHAR(30) NOT NULL);

-- desc AIRPORT;

CREATE TABLE PRICEDETAILS(AIRLINE_CODE VARCHAR(15) NOT NULL,FLIGHT_NUMBER NUMBER,
CLASS1 NUMBER,CLASS2 NUMBER,CLASS3 NUMBER,
PRIMARY KEY(AIRLINE_CODE,FLIGHT_NUMBER),
FOREIGN KEY(AIRLINE_CODE) REFERENCES AIRLINES(AIRLINE_CODE),
FOREIGN KEY(FLIGHT_NUMBER) REFERENCES FLIGHT(FLIGHT_NUMBER));
-- desc AIRLINES;

CREATE TABLE FLIGHT(FLIGHT_NUMBER NUMBER PRIMARY KEY,
AIRLINE_CODE VARCHAR(15),DESTINATION VARCHAR(32),SEAT_CAPACITY NUMBER,FLIGHT_TYPE VARCHAR(32),
FOREIGN KEY(AIRLINE_CODE) REFERENCES AIRLINES(AIRLINE_CODE));

CREATE TABLE FLIGHT_DESTINATION_AIRPORT(FLIGHT_NUMBER NUMBER,AIRPORT_CODE VARCHAR(15),
FOREIGN KEY(AIRPORT_CODE) REFERENCES AIRPORT(AIRPORT_CODE),
FOREIGN KEY(FLIGHT_NUMBER) REFERENCES FLIGHT(FLIGHT_NUMBER));

CREATE TABLE FLIGHT_ARRIVAL_AIRPORT(FLIGHT_NUMBER NUMBER,AIRPORT_CODE VARCHAR(15),
FOREIGN KEY(AIRPORT_CODE) REFERENCES AIRPORT(AIRPORT_CODE),
FOREIGN KEY(FLIGHT_NUMBER) REFERENCES FLIGHT(FLIGHT_NUMBER));

CREATE TABLE PASSENGER(PASSENGER_ID NUMBER PRIMARY KEY,FIRSTNAME VARCHAR(32) NOT NULL,
MIDDLENAME VARCHAR(32),LASTNAME VARCHAR(32) NOT NULL,DOB DATE NOT NULL,
AGE NUMBER CHECK(LENGTH(AGE)>0),GENDER CHAR(1),PASSENGER_TYPE VARCHAR(32));




